<script>
window.DCS_ADMIN_UPDATE_CONFIG = {
    csrfToken: <?= json_encode(getCSRFToken()) ?>,
    demoRestricted: <?= json_encode($demoRestricted) ?>,
    demoRestrictionMessage: <?= json_encode(demoRestrictionMessage()) ?>,
    currentVersion: <?= json_encode(ADMIN_PANEL_VERSION) ?>,
    i18n: <?= json_encode([
        'supportCopied' => dcs_t('admin.update.support_copied'),
        'unavailable' => dcs_t('admin.update.unavailable'),
        'updateReady' => dcs_t('admin.update.update_ready'),
        'latestCodeAvailable' => dcs_t('admin.update.latest_code_available'),
        'updateNow' => dcs_t('admin.update.update_now'),
        'upToDate' => dcs_t('admin.update.up_to_date'),
        'upToDateDetail' => dcs_t('admin.update.up_to_date_detail'),
        'githubFailed' => dcs_t('admin.update.github_check_failed'),
        'githubFailedDetail' => dcs_t('admin.update.github_failed_detail'),
        'unknownStatus' => dcs_t('admin.update.unknown_status'),
        'unknownStatusDetail' => dcs_t('admin.update.unknown_status_detail'),
        'failedCheck' => dcs_t('admin.update.failed_check'),
        'startingUpdate' => dcs_t('admin.update.starting_update', ['channel' => $updateChannel['channel']]),
        'backupDate' => dcs_t('admin.update.backup_date'),
        'version' => dcs_t('admin.update.version'),
        'branch' => dcs_t('admin.update.branch'),
        'size' => dcs_t('admin.update.size'),
        'status' => dcs_t('admin.update.status'),
        'actions' => dcs_t('admin.update.actions'),
        'protected' => dcs_t('admin.update.protected'),
        'autoDeleted' => dcs_t('admin.update.auto_deleted'),
        'restore' => dcs_t('admin.update.restore'),
        'delete' => dcs_t('admin.update.delete'),
        'keepsBackups' => dcs_t('admin.update.keeps_backups'),
        'noBackups' => dcs_t('admin.update.no_backups'),
        'failedLoadBackups' => dcs_t('admin.update.failed_load_backups'),
        'confirmRestore' => dcs_t('admin.update.confirm_restore'),
        'startingRestore' => dcs_t('admin.update.starting_restore'),
        'restoreFailed' => dcs_t('admin.update.restore_failed'),
        'confirmDelete' => dcs_t('admin.update.confirm_delete'),
        'failedDelete' => dcs_t('admin.update.failed_delete'),
        'creatingBackup' => dcs_t('admin.update.creating_backup'),
        'checkingUpdates' => dcs_t('admin.update.checking_updates'),
        'failedCheckUpdates' => dcs_t('admin.update.failed_check_updates'),
        'noBackupsAvailable' => dcs_t('admin.update.no_backups_available'),
        'selectVersion' => dcs_t('admin.update.select_version'),
        'pleaseSelectVersion' => dcs_t('admin.update.please_select_version'),
        'downgradingTo' => dcs_t('admin.update.downgrading_to')
    ], JSON_UNESCAPED_UNICODE) ?>
};
</script>
<script src="../js/admin/update.js"></script>
