version: '3.8'

services:
  dcs-stats-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dcs-stats-website
    ports:
      - "${WEB_PORT:-8080}:80"
    # volumes:
    #   # For development: mount source code (uncomment for development)
    #   - ./dcs-stats:/var/www/html:rw
    environment:
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
      - PHP_MAX_UPLOAD=${PHP_MAX_UPLOAD:-50M}
      - PHP_MAX_FILE_UPLOADS=${PHP_MAX_FILE_UPLOADS:-20}
      - TZ=${TZ:-UTC}
    restart: unless-stopped
    networks:
      - dcs-stats-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dcs-stats-network:
    driver: bridge