services:
  dcs-stats:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-8.2}
    image: dcs-statistics:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-dcs-statistics}
    hostname: ${HOSTNAME:-dcs-stats}
    ports:
      - "${WEB_PORT:-8080}:${INTERNAL_PORT:-80}"
    volumes:
      # Mount the entire dcs-stats directory
      # Windows users: Docker Desktop handles path conversion automatically
      - ./dcs-stats:/var/www/html:rw
    environment:
      # Server Configuration
      - RUN_AS_ROOT=${RUN_AS_ROOT:-false}
      
      # PHP Configuration
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-300}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-50M}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-50M}
      - PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME:-300}
      - PHP_MAX_INPUT_VARS=${PHP_MAX_INPUT_VARS:-1000}
      - PHP_SESSION_TIMEOUT=${PHP_SESSION_TIMEOUT:-1440}
      - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS:-Off}
      - PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-E_ALL & ~E_DEPRECATED & ~E_STRICT}
      
      # Security Configuration
      - ADMIN_SESSION_NAME=${ADMIN_SESSION_NAME:-DCS_ADMIN_SESSION}
      - ENFORCE_HTTPS=${ENFORCE_HTTPS:-false}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-60}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-60}
      
      # Application Configuration  
      - SITE_URL=${SITE_URL:-http://localhost:8080}
      - TZ=${TIMEZONE:-UTC}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - MAINTENANCE_MODE=${MAINTENANCE_MODE:-false}
      - MAINTENANCE_ALLOWED_IPS=${MAINTENANCE_ALLOWED_IPS:-}
      
      # Cache Configuration
      - CACHE_ENABLED=${CACHE_ENABLED:-true}
      - CACHE_TTL=${CACHE_TTL:-300}
      - CACHE_PATH=${CACHE_PATH:-/var/www/html/data/cache}
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - dcs-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health-check.php"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START:-30s}
    labels:
      - "com.dcs-statistics.description=DCS Statistics Web Dashboard"
      - "com.dcs-statistics.version=${VERSION:-1.0}"
      - "com.dcs-statistics.maintainer=${MAINTAINER:-admin@example.com}"
    logging:
      driver: ${LOG_DRIVER:-json-file}
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILES:-3}
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-2}
          memory: ${MEMORY_LIMIT:-512M}
        reservations:
          cpus: ${CPU_RESERVATION:-0.5}
          memory: ${MEMORY_RESERVATION:-256M}

networks:
  dcs-network:
    driver: bridge

# No named volumes needed - everything is in the bind mount