<script>
window.DCS_PILOT_STATISTICS_CONFIG = {
    i18n: <?php echo json_encode([
        'enterName' => dcs_t('pilot.enter_name'),
        'noMatches' => dcs_t('pilot.no_matches'),
        'checkSpelling' => dcs_t('pilot.check_spelling'),
        'usePartial' => dcs_t('pilot.use_partial'),
        'searchStart' => dcs_t('pilot.search_start'),
        'searchError' => dcs_t('pilot.search_error'),
        'loadError' => dcs_t('pilot.load_error'),
        'consoleDetails' => dcs_t('pilot.console_details'),
        'noPilotFound' => dcs_t('pilot.no_pilot_found'),
        'noStatsEnabled' => dcs_t('pilot.no_stats_enabled'),
        'contactAdmin' => dcs_t('pilot.contact_admin'),
        'kills' => dcs_t('pilot.kills'),
        'deaths' => dcs_t('pilot.deaths'),
        'kdRatio' => dcs_t('pilot.kd_ratio'),
        'takeoffs' => dcs_t('pilot.takeoffs'),
        'landings' => dcs_t('pilot.landings'),
        'crashes' => dcs_t('pilot.crashes'),
        'ejections' => dcs_t('pilot.ejections'),
        'credits' => dcs_t('pilot.credits'),
        'mostUsedAircraft' => dcs_t('pilot.most_used_aircraft'),
        'squadron' => dcs_t('pilot.squadron'),
        'none' => dcs_t('pilot.none'),
        'sessionKills' => dcs_t('pilot.session_kills'),
        'sessionDeaths' => dcs_t('pilot.session_deaths'),
        'statistics' => dcs_t('pilot.statistics'),
        'count' => dcs_t('pilot.count'),
        'combatMetrics' => dcs_t('pilot.combat_metrics'),
        'numberOfEvents' => dcs_t('pilot.number_of_events'),
        'combatStats' => dcs_t('pilot.combat_stats'),
        'successfulLandings' => dcs_t('pilot.successful_landings'),
        'inFlight' => dcs_t('pilot.in_flight'),
        'timesUsed' => dcs_t('pilot.times_used'),
        'aircraftType' => dcs_t('pilot.aircraft_type'),
        'carrierLandings' => dcs_t('pilot.carrier_landings'),
        'loadingTraps' => dcs_t('pilot.loading_traps'),
        'noTrapData' => dcs_t('pilot.no_trap_data'),
        'trapLoadError' => dcs_t('pilot.trap_load_error'),
        'trapLatestGrade' => dcs_t('pilot.trap_latest_grade'),
        'trapLatestPoints' => dcs_t('pilot.trap_latest_points'),
        'trapLatestWire' => dcs_t('pilot.trap_latest_wire'),
        'trapLatestAircraft' => dcs_t('pilot.trap_latest_aircraft'),
        'trapLatestCase' => dcs_t('pilot.trap_latest_case'),
        'trapLatestLocation' => dcs_t('pilot.trap_latest_location')
    ], JSON_UNESCAPED_UNICODE); ?>,
    siteFeatures: <?php echo json_encode([
        'credits' => isFeatureEnabled('credits_enabled'),
        'squadrons' => isFeatureEnabled('squadrons_enabled'),
        'leaderboard_kills' => isFeatureEnabled('leaderboard_kills'),
        'leaderboard_deaths' => isFeatureEnabled('leaderboard_deaths'),
        'leaderboard_kd_ratio' => isFeatureEnabled('leaderboard_kd_ratio'),
        'leaderboard_aircraft' => isFeatureEnabled('leaderboard_aircraft'),
        'pilot_combat_stats' => isFeatureEnabled('pilot_combat_stats'),
        'pilot_flight_stats' => isFeatureEnabled('pilot_flight_stats'),
        'pilot_session_stats' => isFeatureEnabled('pilot_session_stats'),
        'pilot_aircraft_chart' => isFeatureEnabled('pilot_aircraft_chart'),
        'pilot_carrier_traps' => isFeatureEnabled('pilot_carrier_traps')
    ]); ?>,
    publicDateFormat: <?php echo json_encode(dcs_public_date_format()); ?>
};
</script>
<script src="<?php echo htmlspecialchars(assetUrl('js/pages/pilot-statistics.js'), ENT_QUOTES, 'UTF-8'); ?>"></script>
