<?php
$storedContent = (string)($editPage['content'] ?? '');
$editorContent = ($editPage['content_format'] ?? 'plain_text') === 'rich_html'
    ? (new \DcsStats\Services\Cms\CmsHtmlSanitizer())->sanitize($storedContent)
    : ($storedContent !== '' ? '<p>' . nl2br(e($storedContent)) . '</p>' : '<p><br></p>');
$editorContent = preg_replace('#src="/?uploads/pages/#', 'src="../uploads/pages/', $editorContent);
?>
<!DOCTYPE html><html lang="<?= e(dcs_default_language()) ?>"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= e($pageTitle) ?> - DCS Statistics</title><link rel="stylesheet" href="css/admin.css"></head>
<body><div class="admin-wrapper"><?php require DCS_APP_PATH . '/Views/Admin/partials/nav.php'; ?><main class="admin-main">
<header class="admin-header"><h1><?= e($pageTitle) ?></h1><div class="admin-user-menu"><div class="admin-user-info"><div class="admin-username"><?= e($currentAdmin['username']) ?></div><div class="admin-role"><?= getRoleBadge($currentAdmin['role']) ?></div></div><?php require DCS_APP_PATH . '/Views/Admin/partials/logout_form.php'; ?></div></header>
<div class="admin-content"><?php if ($message): ?><div class="alert alert-<?= $messageType === 'success' ? 'success' : 'error' ?>"><?= e($message) ?></div><?php endif; ?>
<div class="card"><div class="card-header cms-editor-page-header"><h2 class="card-title"><?= e($pageTitle) ?></h2><a class="btn btn-secondary" href="cms_pages.php"><?= e(dcs_t('admin.cms.back_to_pages')) ?></a></div>
<form method="POST" id="cms-page-form"><?= csrfField() ?><input type="hidden" name="page_id" value="<?= e($editPage['id'] ?? '') ?>">
<div class="cms-editor-details-grid"><div class="form-group"><label for="cms_title"><?= e(dcs_t('admin.cms.title')) ?></label><input class="form-control" id="cms_title" name="title" maxlength="120" required value="<?= e($editPage['title'] ?? '') ?>"></div><div class="form-group"><label for="cms_slug"><?= e(dcs_t('admin.cms.slug')) ?></label><input class="form-control" id="cms_slug" name="slug" maxlength="80" pattern="[a-z0-9-]+" required value="<?= e($editPage['slug'] ?? '') ?>" placeholder="recruitment"></div></div>
<div class="form-group"><label for="cms_content_editor"><?= e(dcs_t('admin.cms.content')) ?></label>
<div class="cms-editor" data-cms-editor><div class="cms-editor-toolbar" role="toolbar" aria-label="<?= e(dcs_t('admin.cms.editor_toolbar')) ?>">
<select class="cms-editor-format" data-editor-format aria-label="<?= e(dcs_t('admin.cms.text_style')) ?>"><option value="p"><?= e(dcs_t('admin.cms.style_paragraph')) ?></option><option value="h2"><?= e(dcs_t('admin.cms.style_heading_2')) ?></option><option value="h3"><?= e(dcs_t('admin.cms.style_heading_3')) ?></option><option value="h4"><?= e(dcs_t('admin.cms.style_heading_4')) ?></option><option value="blockquote"><?= e(dcs_t('admin.cms.style_quote')) ?></option></select><span class="cms-editor-divider"></span>
<?php foreach (['bold'=>'B','italic'=>'I','underline'=>'U','insertUnorderedList'=>'• ≡','insertOrderedList'=>'1. ≡','removeFormat'=>'Tx','undo'=>'↶','redo'=>'↷'] as $command => $symbol): ?><button type="button" data-editor-command="<?= e($command) ?>"><?= $symbol ?></button><?php endforeach; ?>
<span class="cms-editor-divider"></span><button type="button" data-editor-command="justifyLeft" title="<?= e(dcs_t('admin.cms.align_text_left')) ?>" aria-label="<?= e(dcs_t('admin.cms.align_text_left')) ?>">≡←</button><button type="button" data-editor-command="justifyCenter" title="<?= e(dcs_t('admin.cms.align_text_center')) ?>" aria-label="<?= e(dcs_t('admin.cms.align_text_center')) ?>">≡</button><button type="button" data-editor-command="justifyRight" title="<?= e(dcs_t('admin.cms.align_text_right')) ?>" aria-label="<?= e(dcs_t('admin.cms.align_text_right')) ?>">→≡</button>
<button type="button" data-editor-link title="<?= e(dcs_t('admin.cms.add_link')) ?>">🔗</button><button type="button" data-editor-media title="<?= e(dcs_t('admin.cms.add_image')) ?>">🖼️</button><span class="cms-editor-divider"></span><select class="cms-editor-format cms-editor-widget-select" data-editor-widget aria-label="<?= e(dcs_t('admin.cms.widgets')) ?>"><option value=""><?= e(dcs_t('admin.cms.widgets')) ?></option><?php if ($galleryEnabled && $galleries): ?><optgroup label="<?= e(dcs_t('admin.cms.widget_group_general')) ?>"><option value="image-gallery"><?= e(dcs_t('admin.cms.image_gallery')) ?></option></optgroup><?php endif; ?><optgroup label="<?= e(dcs_t('admin.cms.widget_group_statistics')) ?>"><option value="server-status"><?= e(dcs_t('admin.cms.server_status')) ?></option><?php foreach (['summary','attendance','top-pilots','combat-stats','top-squadrons','player-activity','top-theatres','top-missions','top-modules'] as $dashboardWidget): ?><option value="dashboard:<?= e($dashboardWidget) ?>"><?= e(dcs_t('admin.cms.widget_' . str_replace('-', '_', $dashboardWidget))) ?></option><?php endforeach; ?></optgroup></select></div>
<div class="cms-editor-content" id="cms_content_editor" contenteditable="true" role="textbox" aria-multiline="true"><?= $editorContent ?></div><textarea id="cms_content" name="content" maxlength="200000" hidden><?= e($storedContent) ?></textarea></div>
<div class="cms-media-panel" data-media-panel hidden><div class="cms-media-panel-header"><div><strong><?= e(dcs_t('admin.cms.media_library')) ?></strong><p class="text-muted"><?= e(dcs_t('admin.cms.media_help')) ?></p></div><button type="button" class="btn btn-secondary btn-small" data-media-close><?= e(dcs_t('admin.cms.close')) ?></button></div>
<div class="cms-media-insert-options"><label><span><?= e(dcs_t('admin.cms.image_alt')) ?></span><input class="form-control" type="text" maxlength="300" data-media-alt></label><label><span><?= e(dcs_t('admin.cms.image_caption')) ?></span><input class="form-control" type="text" maxlength="300" data-media-caption></label><label><span><?= e(dcs_t('admin.cms.image_alignment')) ?></span><select class="form-control" data-media-alignment><option value="cms-image-center"><?= e(dcs_t('admin.cms.align_center')) ?></option><option value="cms-image-left"><?= e(dcs_t('admin.cms.align_left')) ?></option><option value="cms-image-right"><?= e(dcs_t('admin.cms.align_right')) ?></option><option value="cms-image-wide"><?= e(dcs_t('admin.cms.align_wide')) ?></option></select></label></div>
<div class="cms-media-upload-row"><input class="form-control" type="file" accept="image/jpeg,image/png,image/webp" data-media-file><button type="button" class="btn btn-primary" data-media-upload><?= e(dcs_t('admin.cms.upload_image')) ?></button><span data-media-status></span></div><div class="cms-media-grid" data-media-grid></div></div></div>
<details class="cms-seo-panel" open><summary><?= e(dcs_t('admin.cms.seo_settings')) ?></summary><div class="cms-seo-fields"><div class="form-group"><label for="seo_title"><?= e(dcs_t('admin.cms.seo_title')) ?></label><input class="form-control" id="seo_title" name="seo_title" maxlength="70" value="<?= e($editPage['seo_title'] ?? '') ?>"></div><div class="form-group"><label for="seo_description"><?= e(dcs_t('admin.cms.seo_description')) ?></label><textarea class="form-control" id="seo_description" name="seo_description" maxlength="160" rows="3"><?= e($editPage['seo_description'] ?? '') ?></textarea></div><div class="form-group"><label for="seo_image"><?= e(dcs_t('admin.cms.seo_image')) ?></label><select class="form-control" id="seo_image" name="seo_image"><option value=""><?= e(dcs_t('admin.cms.seo_image_none')) ?></option><?php foreach ($mediaItems as $media): ?><option value="<?= e($media['path']) ?>" <?= ($editPage['seo_image'] ?? '') === $media['path'] ? 'selected' : '' ?>><?= e($media['original_name']) ?></option><?php endforeach; ?></select></div></div></details>
<div class="cms-publish-options"><label><input type="checkbox" name="published" value="1" <?= !empty($editPage['published']) ? 'checked' : '' ?>> <?= e(dcs_t('admin.cms.published')) ?></label><label><input type="checkbox" name="show_in_navigation" value="1" <?= !empty($editPage['show_in_navigation']) ? 'checked' : '' ?>> <?= e(dcs_t('admin.cms.show_navigation')) ?></label></div>
<div class="settings-actions"><button class="btn btn-primary" type="submit"><?= e(dcs_t('admin.cms.save_page')) ?></button><?php if ($editPage): ?><a class="btn btn-secondary" target="_blank" rel="noopener" href="../page_preview.php?id=<?= e($editPage['id']) ?>"><?= e(dcs_t('admin.cms.preview')) ?></a><?php endif; ?><a class="btn btn-secondary" href="cms_pages.php"><?= e(dcs_t('admin.cms.cancel')) ?></a></div></form></div></div></main></div>
<script>window.DCS_CMS_EDITOR_TEXT=<?= json_encode(['linkPrompt'=>dcs_t('admin.cms.link_prompt'),'contentRequired'=>dcs_t('admin.cms.content_required'),'altRequired'=>dcs_t('admin.cms.image_alt_required'),'insertImage'=>dcs_t('admin.cms.insert_image'),'deleteImage'=>dcs_t('admin.cms.delete_image'),'deleteConfirm'=>dcs_t('admin.cms.media_delete_confirm'),'imageInEditor'=>dcs_t('admin.cms.media_in_use_editor'),'emptyLibrary'=>dcs_t('admin.cms.media_empty'),'uploading'=>dcs_t('admin.cms.media_uploading'),'requestFailed'=>dcs_t('admin.cms.media_request_failed'),'networkFailed'=>dcs_t('admin.cms.media_network_failed'),'tooLarge'=>dcs_t('admin.cms.media_proxy_too_large'),'serverStatus'=>dcs_t('admin.cms.server_status'),'imageGallery'=>dcs_t('admin.cms.image_gallery'),'selectGallery'=>dcs_t('admin.cms.select_gallery'),'removeWidget'=>dcs_t('admin.cms.remove_widget'),'saveWidget'=>dcs_t('admin.cms.save_widget'),'widgetSaving'=>dcs_t('admin.cms.widget_saving'),'selectServer'=>dcs_t('admin.cms.select_server'),'allServers'=>dcs_t('admin.cms.all_servers'),'serversUnavailable'=>dcs_t('admin.cms.servers_unavailable'),'metric'=>dcs_t('admin.cms.widget_metric'),'limit'=>dcs_t('admin.cms.widget_limit')], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;window.DCS_CMS_MEDIA=<?= json_encode(['csrfToken'=>getCSRFToken(),'endpoint'=>'api/cms_media.php','items'=>array_values($mediaItems)], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;window.DCS_CMS_WIDGET_CONFIG=<?= json_encode(['serversEndpoint'=>'../get_servers.php','galleries'=>array_map(static fn(array $gallery): array => ['id'=>(string)$gallery['id'],'title'=>(string)$gallery['title']], $galleries),'dashboardWidgets'=>array_combine(['summary','attendance','top-pilots','combat-stats','top-squadrons','player-activity','top-theatres','top-missions','top-modules'], array_map(static fn(string $key): string => dcs_t('admin.cms.widget_' . str_replace('-', '_', $key)), ['summary','attendance','top-pilots','combat-stats','top-squadrons','player-activity','top-theatres','top-missions','top-modules'])),'metrics'=>['kills'=>dcs_t('home.kills'),'kdr'=>dcs_t('home.kill_death_ratio'),'kdr_pvp'=>dcs_t('home.pvp_kill_death_ratio')]], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;</script><script src="../js/admin/cms-editor.js"></script></body></html>
