<!DOCTYPE html>
<html lang="<?= e(dcs_default_language()) ?>">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= e($pageTitle) ?> - DCS Statistics</title><link rel="stylesheet" href="css/admin.css"><link rel="stylesheet" href="../css/admin/cms.css"></head>
<body><div class="admin-wrapper"><?php require DCS_APP_PATH . '/Views/Admin/partials/nav.php'; ?><main class="admin-main">
<header class="admin-header"><h1><?= e($pageTitle) ?></h1><div class="admin-user-menu"><div class="admin-user-info"><div class="admin-username"><?= e($currentAdmin['username']) ?></div><div class="admin-role"><?= getRoleBadge($currentAdmin['role']) ?></div></div><?php require DCS_APP_PATH . '/Views/Admin/partials/logout_form.php'; ?></div></header>
<div class="admin-content"><?php if ($message): ?><div class="alert alert-<?= $messageType === 'success' ? 'success' : 'error' ?>"><?= e($message) ?></div><?php endif; ?>

<section class="card cms-gallery-settings"><div class="card-header"><div><h2 class="card-title"><?= e(dcs_t('admin.cms.gallery_availability')) ?></h2><p class="text-muted"><?= e(dcs_t('admin.cms.gallery_enable_help')) ?></p></div></div>
<form method="POST"><?= csrfField() ?><input type="hidden" name="action" value="save_settings"><label class="cms-setting-toggle"><input type="checkbox" name="cms_gallery_enabled" value="1" <?= $galleryEnabled ? 'checked' : '' ?>><span><strong><?= e(dcs_t('admin.cms.enable_gallery')) ?></strong></span></label><div class="settings-actions"><button class="btn btn-primary" type="submit"><?= e(dcs_t('admin.cms.save_settings')) ?></button></div></form></section>

<?php if ($galleryEnabled): ?>
<div class="cms-gallery-admin-grid"><section class="card"><div class="card-header"><div><h2 class="card-title"><?= e(dcs_t('admin.cms.existing_galleries')) ?></h2><p class="text-muted"><?= e(dcs_t('admin.cms.galleries_help')) ?></p></div><a class="btn btn-primary" href="cms_galleries.php"><?= e(dcs_t('admin.cms.create_gallery')) ?></a></div>
<?php if (!$galleries): ?><p class="cms-empty-state"><?= e(dcs_t('admin.cms.no_galleries')) ?></p><?php endif; ?>
<div class="cms-gallery-list"><?php foreach ($galleries as $gallery): ?><article><div><strong><?= e($gallery['title'] ?? '') ?></strong><small class="text-muted"><?= count((array)($gallery['items'] ?? [])) ?> <?= e(dcs_t('admin.cms.images')) ?> · <?= e(dcs_t(!empty($gallery['enabled']) ? 'admin.cms.published' : 'admin.cms.draft')) ?></small></div><div class="cms-page-actions"><a class="btn btn-secondary btn-small" href="cms_galleries.php?edit=<?= e($gallery['id']) ?>"><?= e(dcs_t('admin.cms.edit')) ?></a><form method="POST" onsubmit="return confirm(<?= e(json_encode(dcs_t('admin.cms.confirm_delete_gallery'))) ?>);">
<?= csrfField() ?><input type="hidden" name="action" value="delete_gallery"><input type="hidden" name="gallery_id" value="<?= e($gallery['id']) ?>"><button class="btn btn-danger btn-small" type="submit"><?= e(dcs_t('admin.cms.delete')) ?></button></form></div></article><?php endforeach; ?></div></section>

<section class="card"><div class="card-header"><div><h2 class="card-title"><?= e(dcs_t($editGallery ? 'admin.cms.edit_gallery' : 'admin.cms.create_gallery')) ?></h2><p class="text-muted"><?= e(dcs_t('admin.cms.gallery_form_help')) ?></p></div></div>
<form method="POST"><?= csrfField() ?><input type="hidden" name="action" value="save_gallery"><input type="hidden" name="gallery_id" value="<?= e($editGallery['id'] ?? '') ?>">
<div class="form-group"><label for="gallery-title"><?= e(dcs_t('admin.cms.gallery_title')) ?></label><input class="form-control" id="gallery-title" name="title" maxlength="120" required value="<?= e($editGallery['title'] ?? '') ?>"></div>
<label class="cms-setting-toggle"><input type="checkbox" name="enabled" value="1" <?= !isset($editGallery['enabled']) || !empty($editGallery['enabled']) ? 'checked' : '' ?>><span><strong><?= e(dcs_t('admin.cms.gallery_published')) ?></strong></span></label>
<?php $selectedItems = []; foreach ((array)($editGallery['items'] ?? []) as $selected) $selectedItems[(string)($selected['media_id'] ?? '')] = $selected; ?>
<div class="cms-gallery-picker"><?php foreach ($mediaItems as $media): ?><?php $selected = $selectedItems[$media['id']] ?? null; ?><label class="cms-gallery-pick-card"><input type="checkbox" name="media_ids[]" value="<?= e($media['id']) ?>" <?= $selected ? 'checked' : '' ?>><img src="../<?= e($media['path']) ?>" alt="" loading="lazy"><strong><?= e($media['original_name']) ?></strong><span><?= e(dcs_t('admin.cms.image_alt')) ?></span><input class="form-control" name="alt[<?= e($media['id']) ?>]" maxlength="300" value="<?= e($selected['alt'] ?? '') ?>"><span><?= e(dcs_t('admin.cms.image_caption')) ?></span><input class="form-control" name="caption[<?= e($media['id']) ?>]" maxlength="300" value="<?= e($selected['caption'] ?? '') ?>"></label><?php endforeach; ?></div>
<?php if (!$mediaItems): ?><p class="text-muted"><?= e(dcs_t('admin.cms.gallery_media_empty')) ?></p><?php endif; ?><div class="settings-actions"><button class="btn btn-primary" type="submit"><?= e(dcs_t('admin.cms.save_gallery')) ?></button></div></form>
<hr><form method="POST" enctype="multipart/form-data" class="cms-gallery-upload"><?= csrfField() ?><input type="hidden" name="action" value="upload_image"><input type="hidden" name="gallery_id" value="<?= e($editGallery['id'] ?? '') ?>"><div><input class="form-control" type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple required><small class="text-muted"><?= e(dcs_t('admin.cms.gallery_batch_help')) ?></small></div><button class="btn btn-secondary" type="submit"><?= e(dcs_t('admin.cms.upload_images')) ?></button></form></section></div>
<?php endif; ?>
</div></main></div></body></html>
